# Generated by Django 3.2.25 on 2024-03-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='NIM',
            new_name='Card',
        ),
        migrations.RemoveField(
            model_name='student',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Apps1.gender'),
        ),
    ]
